name: Lint & Typecheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        run: corepack prepare pnpm@10.15.0 --activate

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Typecheck (workspace)
        run: pnpm typecheck

      - name: Build (ensure projects compile)
        run: pnpm -r build
